FROM node:22.20.1-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Next.js telemetry disable is good practice in container dev
ENV NEXT_TELEMETRY_DISABLED=1

# Source code is mounted at runtime.
CMD ["npm", "run", "dev"]
